# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20160818_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='custom_message',
            new_name='custom_Message',
        ),
    ]
