# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20160818_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='custom_Message',
            new_name='message',
        ),
    ]
